"""add document uri fields

Revision ID: 032b9159cf29
Revises: e833ebbd4392
Create Date: 2026-07-20 13:58:41.720876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032b9159cf29'
down_revision: Union[str, Sequence[str], None] = 'e833ebbd4392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_uri', sa.String(), nullable=False))
    op.alter_column('document', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('PENDING', 'PROCESSING', 'UPLOADED', 'FAILED', 'PARSING', 'PARSED', 'PARSING_FAILED', 'CHUNKING', 'CHUNKED', name='document_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'UPLOADED', 'FAILED', 'PARSING', 'PARSED', 'PARSING_FAILED', 'CHUNKING', 'CHUNKED', name='document_status', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('document', 'doc_uri')
    # ### end Alembic commands ###
