"""update documents table

Revision ID: e833ebbd4392
Revises: e784fccf6207
Create Date: 2026-07-16 16:02:20.661733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e833ebbd4392'
down_revision: Union[str, Sequence[str], None] = 'e784fccf6207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('document', sa.Column('doc_metadata', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('uq_user_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('document', 'doc_metadata')
    op.drop_column('document', 'mime_type')
    # ### end Alembic commands ###
