"""add document parsing fields

Revision ID: feb8a8c64c37
Revises: 032b9159cf29
Create Date: 2026-07-20 15:00:20.355799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feb8a8c64c37'
down_revision: Union[str, Sequence[str], None] = '032b9159cf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_parsing',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PARSING_QUEUED', 'PARSING', 'PARSED', 'FAILED', name='document_parsing_status', native_enum=False), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('character_count', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parser_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('parser_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('parse_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_parsing_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_parsing'))
    )
    op.create_index(op.f('ix_document_parsing_document_id'), 'document_parsing', ['document_id'], unique=True)
    op.drop_index(op.f('ix_document_chunk_document_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    op.alter_column('document', 'status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status', native_enum=False),
               existing_nullable=False)
    op.drop_column('document', 'content_type')
    op.drop_column('document', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('document', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('document', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status', native_enum=False),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    op.create_table('document_chunk',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_chunk_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunk')),
    sa.UniqueConstraint('document_id', 'chunk_index', name=op.f('uq_document_chunks_document_id_chunk_index'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_document_chunk_document_id'), 'document_chunk', ['document_id'], unique=False)
    op.drop_index(op.f('ix_document_parsing_document_id'), table_name='document_parsing')
    op.drop_table('document_parsing')
    # ### end Alembic commands ###
